version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/server-config"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
